import React, { useState, useEffect } from 'react';
import './Design.css';

const PsdGnrtr = () => {
  const [password, setPassword] = useState('');
  const [length, setLength] = useState(10);
  const [numbers, setNumbers] = useState(true);
  const [alphabets, setAlphabets] = useState(true);
  const [specialChars, setSpecialChars] = useState(true);
  const [copy, setCopy] = useState(false);
  const [passwordHistory, setPasswordHistory] = useState([]);

  

  const psdGenerated = () => {
    const numbers = '0123456789';
    const alphabets = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const specialChars = '!@#$%^&*()_+[]{}|;:,.<>?';

    let characters = '';

    if (numbers) {
      characters += numbers;
    }

    if (alphabets) {
      characters += alphabets;
    }

    if (specialChars) {
      characters += specialChars;
    }

    let newPasswordText = '';
    for (let i = 0; i < length; i++) {
      const randomIndex = Math.floor(Math.random() * characters.length);
      newPasswordText += characters.charAt(randomIndex);
    }

    const newPassword = {
      value: newPasswordText,
    //   timestamp: new Date().toLocaleString(),
    };

    setPassword(newPasswordText);
    setCopy(false);

    setPasswordHistory((prevHistory) => [newPassword, ...prevHistory.slice(0, 4)]);
  };

  const copyToClipboard = () => {
    const passwordInput = document.getElementById('passwordInput');

    if (passwordInput) {
      passwordInput.select();
      document.execCommand('copy');
      setCopy(true);
    }
  };




  const GeneratedPswrds = () => {
    return (
      <div className="password-history">
        <h2>Last 5 Passwords generated by User</h2>
        <ul>
          {passwordHistory.map((password, index) => (
            <li key={index}>
              <span>{password.value}</span>
              {/* <span>{password.timestamp}</span> */}
            </li>
          ))}
        </ul>
      </div>
    );
  };

  
 

  useEffect(() => {
    // Check if there's existing data in localStorage
    const storedPasswordHistory = localStorage.getItem('passwordHistory');
    if (storedPasswordHistory) {
      setPasswordHistory(JSON.parse(storedPasswordHistory));
    }
  }, []);

  useEffect(() => {
    // Save password history to localStorage whenever it changes
    localStorage.setItem('passwordHistory', JSON.stringify(passwordHistory));
  }, [passwordHistory]);

  return (
    <div className="container">
      <h1>Password Generator</h1>
      <div className='length-label'>
        <div className='heading'>Password Length  </div>
        <input
          type="range"
          value={length}
          onChange={(e) => setLength(e.target.value)}
        />
      
        <label>{length}</label>
      </div>

      <div className='checkboxes'>
      <div>
        <label>Numbers:</label>
        <input
          type="checkbox"
          checked={numbers}
          onChange={() => setNumbers(!numbers)}
        />
      </div>
      <div>
        <label>Alphabets:</label>
        <input
          type="checkbox"
          checked={alphabets}
          onChange={() => setAlphabets(!alphabets)}
        />
      </div>
      <div>
        <label>Special Characters:</label>
        <input
          type="checkbox"
          checked={specialChars}
          onChange={() => setSpecialChars(!specialChars)}
        />
      </div>

      </div>
      
      <div>
      <div className='buttons'>
        <button onClick={psdGenerated}>Generate Password</button>
        <button onClick={copyToClipboard}>
          {copy ? 'Copy!' : 'Copy to Clipboard'}
        </button>
        </div>
      <h2>Generated Password</h2>
        <input
          id="passwordInput"
          type="text"
          value={password}
          readOnly
        />
       
       
      </div>
      {GeneratedPswrds()}
    </div>
  );
};

export default PsdGnrtr;
